symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600  # Durée de validité du jeton en secondes (ici, 1 heure)
    throttle_limit: 3600  # Délai entre deux demandes de réinitialisation pour le même utilisateur (ici, 1 heure)